{% set name = "printo" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/printo-{{ version }}.tar.gz
  sha256: addbc25fd1cd26b7948bc37b877d4c6b4fe10442cff3a57ab00bf893b6c17fc5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==68.0.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - printo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pomponchik/printo
  summary: Print objects with data beautifully
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
