{% set name = "printo" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/printo-{{ version }}.tar.gz
  sha256: dbaa68a84e814c5c5279b588f07dae51182e2f7e7c9c154aa98a688f0cbf78a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools ==68.0.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - printo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pomponchik/printo
  summary: Print objects with data beautifully
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
