schema_version: 1

context:
  name: printo
  version: "0.0.14"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/printo-${{ version }}.tar.gz
  sha256: d348ad077d73ef559cf56349788cdc891a69beaeb0e9e47322c1e3704f88bb3f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools ==68.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - sigmatch >=0.0.7

tests:
  - python:
      imports:
        - printo
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Print objects with data beautifully
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pomponchik/printo

extra:
  recipe-maintainers:
    - thewchan
