schema_version: 1

context:
  name: printo
  version: 0.0.7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/printo-${{ version }}.tar.gz
  sha256: 29914683b81a6da05d06de803f8c37b8fdf88fe4cb3dea5847220cf03b35278c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools ==68.0.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - printo
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Print objects with data beautifully
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/pomponchik/printo

extra:
  recipe-maintainers:
    - thewchan
